language: java
os: linux
dist: xenial

jdk: 
    - openjdk11

install: 
    - gradle build

script: 
    - gradle test
    - gradle sonarqube -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN